### ISSUE TITLE
FreeRTOS v10.3.1 missing

### ISSUE THREAD

**Issue by jons-lh** [STMicroelectronics/stm32_mw_freertos#1]
### Missing FreeRTOS v10.3.1 
This repository is missing the latest version of stm32_mw_freertos, 10.3.1, which is available in multiple STM32CubeXX repositories/packages (STM32CubeH7, STM32CubeG4, STM32CubeG0, ++). We require the use of these separate libraries instead of the general STM32CubeXX repositories. So keeping these up to date would be very much appreciated.

Thank you for your help.

**Comment by jons-lh** [comment]
@ALABSTM

**Comment by RKOUSTM** [comment]
Hi @jons-lh, 

Thank you for your contribution. 

We have reported your request to our technical team, we plan to publish the latest version v10.3.1 of FreeRTOS on GitHub. We aim to have this version available on GitHub soon. We will keep you informed.

Thank you again for your contribution.

With regards,

**Comment by RKOUSTM** [comment]
Hi @jons-lh,

I hope you are fine.

The latest version v10.3.1 of FreeRTOS is now available on GitHub.

Thank you again for having reported.

With regards,
