### ISSUE TITLE
FreeRTOS 10.4.x

### ISSUE THREAD

**Issue by jonnor** [STMicroelectronics/stm32_mw_freertos#2]
Hi,
currently FreeRTOS 10.3.1 is provided here, released in August 2020.

Are there any plans to provide FreeRTOS 10.4.x? First release Sept 2020, latest release November 2021? 
Or does it maybe exist in another repository?

**Comment by RKOUSTM** [comment]
Hi @jonnor, 

Thank you for your contribution.

Actually, we have planned the publication of the FreeRTOS versions on GitHub that are already integrated on our STM32Cube FW packages. We still cannot share a date for the moment for the upgrade to use the latest FreeRTOS v10.4.x version on our repositories. We will keep you informed.

Thank you again for your contribution.

With regards,
