### ISSUE TITLE
please update your rtos version

### ISSUE THREAD

**Issue by zouzhe1** [STMicroelectronics/stm32_mw_freertos#3]
because 10.3.1 is  20.1.19
now is   10.4.6    21.11.13

**Comment by ALABSTM** [comment]
Hi @zouzhe1,

Seems we missed this one. Please excuse the delay. Version **10.4.6** has already been published since a while.

With regards,

**Comment by ALABSTM** [comment]
Fixed in commit d82bd49a118c63437ad6b8a73f467cd7e383e41d
