### ISSUE TITLE
please include the full text of the licence in the LICENSE.md file

### ISSUE THREAD

**Issue by mohrr** [STMicroelectronics/stm32_mw_freertos#4]
Please include the full text of the licence in the LICENSE.md file as described in https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by ALABSTM** [comment]
Hi @mohrr,

Request forwarded to our development teams. We will keep you updated.

With regards,

**Comment by ALABSTM** [comment]
ST Internal Reference: 155913

**Comment by ALABSTM** [comment]
Hi @mohrr,

Done in the frame of release **10.5.1**. A [LICENSE.md](https://github.com/STMicroelectronics/stm32_mw_freertos/blob/master/LICENSE.md) file is now available at the root of the repository with the **full license terms**.

With regards,
